# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

INFORMATION <- function((MAX_SIG_SIZE+1) {
    .Call('_RadOnc_INFORMATION', PACKAGE = 'RadOnc', (MAX_SIG_SIZE+1)
}

timesTwo <- function(x) {
    .Call('_RadOnc_timesTwo', PACKAGE = 'RadOnc', x)
}

